#!/bin/bash

echo check_docker_logs
./check_docker_logs --max_size_warning=11 --max_size_critical=20 --max_amount_warning=6 --max_amount_critical=20 --run_as=root

echo
echo check_le_certs
./check_le_certs --run_as=root --warning=10 --critical=2
